version: '3'
   
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: lara-doc
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf